function ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D)

figure('Name','Oscilator cu punte Wien',... 
    'Units','normalized',...   
    'Position',[0.1 0.1 0.8 0.8],... 
    'NumberTitle','off','color','y');
f=uimenu('Label','Documentatie');
 uimenu(f,'Label','Titlu proiect','Callback','open(''titlu_proiect.htm'')');
 uimenu(f,'Label','Descriere proiect','Callback','open(''Descriere_proiect.htm'')');
 uimenu(f,'Label','Ecuatii proiect','Callback','open(''Ecuatii_proiect.htm'')');
 uimenu(f,'Label','Utilizarea interfetei','Callback','open(''Utilizarea_interfetei1.htm'')');
 uimenu(f,'Label','Bibliografie','Callback','open(''Bibliografie.htm'')');


  


uicontrol('Style','text',...     %Text C1
    'Units','normalized',... 
    'Position',[0.02 0.9 0.13 0.04],...   
    'String','C1[f] =  '); 
uicontrol('Style','edit',...     %Edit C1
    'Units','normalized',... 
    'Position',[0.16 0.9 0.06 0.03],...
    'String',num2str(C1),...
    'Callback','C1 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D);');
uicontrol('Style','text',...     %Text C2
    'Units','normalized',... 
    'Position',[0.02 0.85 0.13 0.04],...   
    'String','C2[f] =  '); 
uicontrol('Style','edit',...     %Edit C2
    'Units','normalized',... 
    'Position',[0.16 0.85 0.06 0.03],...
    'String',num2str(C2),...
    'Callback','C2 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D);');
uicontrol('Style','text',...     %Text Valim
    'Units','normalized',... 
    'Position',[0.02 0.80 0.13 0.04],...   
    'String','±Valim[V] = '); 
edit2=uicontrol('Style','edit',...     %Edit Valim
    'Units','normalized',... 
    'Position',[0.16 0.80 0.06 0.03],...
    'String',num2str(Valim),...
    'Callback','Valim = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D);');
uicontrol('Style','text',...     %Text R1
    'Units','normalized',... 
    'Position',[0.02 0.75 0.13 0.04],...   
    'String','R1[Ω] =  '); 
uicontrol('Style','edit',...     %Edit R1
    'Units','normalized',... 
    'Position',[0.16 0.75 0.06 0.03],...
    'String',num2str(R1),...
    'Callback','R1 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D);');
uicontrol('Style','text',...     %Text R2
    'Units','normalized',... 
    'Position',[0.02 0.70 0.13 0.04],...   
    'String','R2[Ω] =  '); 
uicontrol('Style','edit',...     %Edit R2
    'Units','normalized',... 
    'Position',[0.16 0.70 0.06 0.03],...
    'String',num2str(R2),...
    'Callback','R2 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D);');
uicontrol('Style','text',...     %Text R3
    'Units','normalized',... 
    'Position',[0.02 0.65 0.13 0.04],...   
    'String','R3[Ω] =  '); 
uicontrol('Style','edit',...     %Edit R3
    'Units','normalized',... 
    'Position',[0.16 0.65 0.06 0.03],...
    'String',num2str(R3),...
    'Callback','R3 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D);');
uicontrol('Style','text',...     %Text R4
    'Units','normalized',... 
    'Position',[0.25 0.90 0.13 0.04],...   
    'String','R4[Ω] =  '); 
uicontrol('Style','edit',...     %Edit R4
    'Units','normalized',... 
    'Position',[0.39 0.90 0.06 0.03],...
    'String',num2str(R4),...
    'Callback','R4 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D);');
uicontrol('Style','text',...     %Text R5
    'Units','normalized',... 
    'Position',[0.25 0.85 0.13 0.04],...   
    'String','R5[Ω] =  '); 
uicontrol('Style','edit',...     %Edit R5
    'Units','normalized',... 
    'Position',[0.39 0.85 0.06 0.03],...
    'String',num2str(R5),...
    'Callback','R5 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D)');
uicontrol('Style','text',...     %Text Conduce 
    'Units','normalized',... 
    'Position',[0.25 0.65 0.13 0.04],...   
    'String','Conduce :  '); 
uicontrol('style','popup',...
    'units','normalized',...
    'position',[0.39 0.65 0.06 0.03],...
    'value', D,...
    'string','dioda 1/dioda2|blocare',...
    'BackgroundColor','g',...
   'callback', 'D=get(gcbo,''value''),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D)')
uicontrol('Style','text',...     %Text a
    'Units','normalized',... 
    'Position',[0.25 0.70 0.13 0.04],...   
    'String','a =  '); 
img=imread('circuit.png');
subplot('position',[0.5 0.5 0.4 0.4]) %afisarea imaginii circuitului
imshow(img,[]);


if (R1==R2||C1==C2)
    f=1/(2*pi*R1*C1);
    r=1/3;
else
    f=1/(2*pi*sqrt(R1*R2*C1*C2));
    r=1/(1+R1/R2+C2/C1);
end
uicontrol('Style','text',...     %Text f0
    'Units','normalized',... 
    'Position',[0.02 0.60 0.13 0.04],...   
    'String','Frecventa[Hz]=  '); 
uicontrol('Style','text',...     %Edit f0
    'Units','normalized',... 
    'Position',[0.16 0.60 0.06 0.03],...
    'String',num2str(f),...
    'Callback','f = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D)');
T=1/f;
t=0:T/100:6*T;
I=0.7/((R4*rd1)/(R4+rd1));
V0=I*R3+I*R5+0.7; 
vt=V0*sin(2*pi*f*t);
vpoz=r*vt;
switch D
     case 1
         a=1+((R5+((R4*rd1)/(R4+rd1)))/R3)
          V0=I*R3+0.7+I*R5;
        vt=V0*sin(2*pi*f*t);
        vpoz=r*vt;
         if(a==3) 
    % a=3 conditia de mentinere a oscilatiilor 
         else
             vt=0;
    error('Nu se respecta conditia de mentinere a oscilatiilor')
    
end
     %case 2
       %a=1+((R5+((R4*rd2)/(R4+rd2)))/R3)
        %V0=I*R3-0.7+I*R5;
        %vt=V0*sin(2*pi*f*t);
        %vpoz=r*vt;
       %if(a==3) 
    % a=3 conditia de mentinere a oscilatiilor 
       %else
           %vt=0;
    %error('Nu se respecta conditia de mentinere a oscilatiilor')
    
%end
     case 2
        a=1+(R4+R5)/R3
        I=0.7/R4;
        V0=I*R3-0.6+I*R5;
        vt=V0*sin(2*pi*f*t);
        vpoz=r*vt;
        if(a<3)
            vt=0;
    error('Nu se respecta conditia de aparitie a oscilatiilor')
   
        end

end

  if(Valim<=V0)
    V0=Valim;
    vt=V0*sin(2*pi*f*t);
        vpoz=r*vt;
        
elseif(-Valim>V0)
    V0=-Valim;
    vt=V0*sin(2*pi*f*t);
        vpoz=r*vt;
      
end

uicontrol('Style','text',...     %Edit a
    'Units','normalized',... 
    'Position',[0.39 0.70 0.06 0.03],...
    'String',num2str(a),...
    'Callback','a = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D)');
uicontrol('Style','text',...     %Text V0
    'Units','normalized',... 
    'Position',[0.25 0.75 0.13 0.04],...   
    'String','V0[V] = '); 
uicontrol('Style','text',...     %Edit V0
    'Units','normalized',... 
    'Position',[0.39 0.75 0.06 0.03],...
    'String',num2str(V0),...
    'Callback','V0 = str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D)');
uicontrol('Style','text',...     %Text Vpoz
    'Units','normalized',... 
    'Position',[0.25 0.80 0.13 0.04],...   
    'String','V+=V-[V] = '); 
uicontrol('Style','text',...     %Edit Vpoz
    'Units','normalized',... 
    'Position',[0.39 0.80 0.06 0.03],...
    'String',num2str(V0/3),...
    'Callback','V+= str2num(get (gco,''String'')),close,ptGac(Valim,C1,C2,R1,R2,R3,R4,R5,rd1,rd2,D)');
Bp=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.85 0.90 0.1 0.05],...
'backgroundcolor','r',...
'foregroundcolor','black',...
'String','CLOSE',...
'Callback','close');


subplot(212)
plot(t,vt,'-or')
hold on;
plot(t,vpoz,':db');
grid on;
title('Semnalul de iesire');%atribuim un titlu graficului
xlabel('timp [s]'); %scriem text pe axa x
ylabel('Amplitudine [V]'); %scriem text pe axa y
legend('vt','V+');
ylim([-Valim Valim])

